// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: meta/v1/meta.proto

package metaapiconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/jumppad-labs/polymorph/pkg/api/meta/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// PolymorphMetaServiceName is the fully-qualified name of the PolymorphMetaService service.
	PolymorphMetaServiceName = "meta.v1.PolymorphMetaService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// PolymorphMetaServiceGetResourcesProcedure is the fully-qualified name of the
	// PolymorphMetaService's GetResources RPC.
	PolymorphMetaServiceGetResourcesProcedure = "/meta.v1.PolymorphMetaService/GetResources"
	// PolymorphMetaServiceGetRequestLogsProcedure is the fully-qualified name of the
	// PolymorphMetaService's GetRequestLogs RPC.
	PolymorphMetaServiceGetRequestLogsProcedure = "/meta.v1.PolymorphMetaService/GetRequestLogs"
)

// These variables are the protoreflect.Descriptor objects for the RPCs defined in this package.
var (
	polymorphMetaServiceServiceDescriptor              = v1.File_meta_v1_meta_proto.Services().ByName("PolymorphMetaService")
	polymorphMetaServiceGetResourcesMethodDescriptor   = polymorphMetaServiceServiceDescriptor.Methods().ByName("GetResources")
	polymorphMetaServiceGetRequestLogsMethodDescriptor = polymorphMetaServiceServiceDescriptor.Methods().ByName("GetRequestLogs")
)

// PolymorphMetaServiceClient is a client for the meta.v1.PolymorphMetaService service.
type PolymorphMetaServiceClient interface {
	// GetResources returns resource schemas for all services on this node
	GetResources(context.Context, *connect.Request[v1.GetResourcesRequest]) (*connect.Response[v1.GetResourcesResponse], error)
	// GetRequestLogs returns recent HTTP request logs for a service
	GetRequestLogs(context.Context, *connect.Request[v1.GetRequestLogsRequest]) (*connect.Response[v1.GetRequestLogsResponse], error)
}

// NewPolymorphMetaServiceClient constructs a client for the meta.v1.PolymorphMetaService service.
// By default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped
// responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewPolymorphMetaServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) PolymorphMetaServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &polymorphMetaServiceClient{
		getResources: connect.NewClient[v1.GetResourcesRequest, v1.GetResourcesResponse](
			httpClient,
			baseURL+PolymorphMetaServiceGetResourcesProcedure,
			connect.WithSchema(polymorphMetaServiceGetResourcesMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		getRequestLogs: connect.NewClient[v1.GetRequestLogsRequest, v1.GetRequestLogsResponse](
			httpClient,
			baseURL+PolymorphMetaServiceGetRequestLogsProcedure,
			connect.WithSchema(polymorphMetaServiceGetRequestLogsMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
	}
}

// polymorphMetaServiceClient implements PolymorphMetaServiceClient.
type polymorphMetaServiceClient struct {
	getResources   *connect.Client[v1.GetResourcesRequest, v1.GetResourcesResponse]
	getRequestLogs *connect.Client[v1.GetRequestLogsRequest, v1.GetRequestLogsResponse]
}

// GetResources calls meta.v1.PolymorphMetaService.GetResources.
func (c *polymorphMetaServiceClient) GetResources(ctx context.Context, req *connect.Request[v1.GetResourcesRequest]) (*connect.Response[v1.GetResourcesResponse], error) {
	return c.getResources.CallUnary(ctx, req)
}

// GetRequestLogs calls meta.v1.PolymorphMetaService.GetRequestLogs.
func (c *polymorphMetaServiceClient) GetRequestLogs(ctx context.Context, req *connect.Request[v1.GetRequestLogsRequest]) (*connect.Response[v1.GetRequestLogsResponse], error) {
	return c.getRequestLogs.CallUnary(ctx, req)
}

// PolymorphMetaServiceHandler is an implementation of the meta.v1.PolymorphMetaService service.
type PolymorphMetaServiceHandler interface {
	// GetResources returns resource schemas for all services on this node
	GetResources(context.Context, *connect.Request[v1.GetResourcesRequest]) (*connect.Response[v1.GetResourcesResponse], error)
	// GetRequestLogs returns recent HTTP request logs for a service
	GetRequestLogs(context.Context, *connect.Request[v1.GetRequestLogsRequest]) (*connect.Response[v1.GetRequestLogsResponse], error)
}

// NewPolymorphMetaServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewPolymorphMetaServiceHandler(svc PolymorphMetaServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	polymorphMetaServiceGetResourcesHandler := connect.NewUnaryHandler(
		PolymorphMetaServiceGetResourcesProcedure,
		svc.GetResources,
		connect.WithSchema(polymorphMetaServiceGetResourcesMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	polymorphMetaServiceGetRequestLogsHandler := connect.NewUnaryHandler(
		PolymorphMetaServiceGetRequestLogsProcedure,
		svc.GetRequestLogs,
		connect.WithSchema(polymorphMetaServiceGetRequestLogsMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	return "/meta.v1.PolymorphMetaService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case PolymorphMetaServiceGetResourcesProcedure:
			polymorphMetaServiceGetResourcesHandler.ServeHTTP(w, r)
		case PolymorphMetaServiceGetRequestLogsProcedure:
			polymorphMetaServiceGetRequestLogsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedPolymorphMetaServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedPolymorphMetaServiceHandler struct{}

func (UnimplementedPolymorphMetaServiceHandler) GetResources(context.Context, *connect.Request[v1.GetResourcesRequest]) (*connect.Response[v1.GetResourcesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("meta.v1.PolymorphMetaService.GetResources is not implemented"))
}

func (UnimplementedPolymorphMetaServiceHandler) GetRequestLogs(context.Context, *connect.Request[v1.GetRequestLogsRequest]) (*connect.Response[v1.GetRequestLogsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("meta.v1.PolymorphMetaService.GetRequestLogs is not implemented"))
}
